import {defineConfig} from "vite";
import {resolve} from "node:path";

/**
 * The site is static HTML generated by `build.mjs` from the hook registry, so Vite's only job is to bundle the
 * client-side modules (the three.js scenes and the catalogue filtering) into hashed assets. `build.mjs` then reads
 * the manifest Vite writes and points every generated page at the right files.
 */
export default defineConfig({
  root: resolve(import.meta.dirname, "."),
  publicDir: resolve(import.meta.dirname, "public"),
  build: {
    outDir: "dist",
    emptyOutDir: true,
    manifest: true,
    assetsDir: "assets",
    rollupOptions: {
      input: {
        app: resolve(import.meta.dirname, "src/main.js"),
        styles: resolve(import.meta.dirname, "src/styles.css"),
      },
      output: {
        // three.js is the bulk of the client bundle and only the home page and hook pages need it, so it goes in its
        // own chunk that the scenes pull in dynamically. The docs pages ship a few kilobytes of JavaScript instead of
        // half a megabyte.
        inlineDynamicImports: false,
        manualChunks: (id) => (id.includes("node_modules/three") ? "three" : undefined),
        entryFileNames: "assets/[name].[hash].js",
        chunkFileNames: "assets/[name].[hash].js",
        assetFileNames: "assets/[name].[hash][extname]",
      },
    },
  },
});
